.PHONY: all clean

all: black.png blue.png green.png red.png white.png yellow.png

black.png: black.svg
	convert -background none black.svg black.png

blue.png: blue.svg
	convert -background none blue.svg blue.png

green.png: green.svg
	convert -background none green.svg green.png

red.png: red.svg
	convert -background none red.svg red.png

white.png: white.svg
	convert -background none white.svg white.png

yellow.png: yellow.svg
	convert -background none yellow.svg yellow.png

clean:
	rm -f black.png blue.png green.png red.png white.png yellow.png
